version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
                - ALPHAVANTAGE_API_KEY=${ALPHAVANTAGE_API_KEY}
                - GOLDAPI_KEY=${GOLDAPI_KEY}
                - GOLDAPI_API_KEY=${GOLDAPI_API_KEY}
        container_name: laravel-app
        restart: unless-stopped
        ports:
            - "8000:80"
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./storage/logs:/var/www/storage/logs
        environment:
            - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
            - ALPHAVANTAGE_API_KEY=${ALPHAVANTAGE_API_KEY}
            - GOLDAPI_KEY=${GOLDAPI_KEY}
            - GOLDAPI_API_KEY=${GOLDAPI_API_KEY}
            - APP_ENV=${APP_ENV}
            - APP_DEBUG=${APP_DEBUG}
        networks:
            - sail
        depends_on:
            - redis
            - postgres
            
    queue-worker:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
                - ALPHAVANTAGE_API_KEY=${ALPHAVANTAGE_API_KEY}
                - GOLDAPI_KEY=${GOLDAPI_KEY}
                - GOLDAPI_API_KEY=${GOLDAPI_API_KEY}
        container_name: queue-worker
        restart: unless-stopped
        command: php artisan queue:work redis --tries=3 --verbose
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./storage/logs:/var/www/storage/logs
        environment:
            - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
            - ALPHAVANTAGE_API_KEY=${ALPHAVANTAGE_API_KEY}
            - GOLDAPI_KEY=${GOLDAPI_KEY}
            - GOLDAPI_API_KEY=${GOLDAPI_API_KEY}
            - APP_ENV=${APP_ENV}
            - APP_DEBUG=${APP_DEBUG}
        networks:
            - sail
        depends_on:
            - redis
            - postgres
            
    scheduler:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
                - ALPHAVANTAGE_API_KEY=${ALPHAVANTAGE_API_KEY}
                - GOLDAPI_KEY=${GOLDAPI_KEY}
                - GOLDAPI_API_KEY=${GOLDAPI_API_KEY}
        container_name: scheduler
        restart: unless-stopped
        command: php artisan schedule:work
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./storage/logs:/var/www/storage/logs
        environment:
            - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
            - ALPHAVANTAGE_API_KEY=${ALPHAVANTAGE_API_KEY}
            - GOLDAPI_KEY=${GOLDAPI_KEY}
            - GOLDAPI_API_KEY=${GOLDAPI_API_KEY}
            - APP_ENV=${APP_ENV}
            - APP_DEBUG=${APP_DEBUG}
        networks:
            - sail
        depends_on:
            - redis
            - postgres
            
    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - sail
        volumes:
            - redis-data:/data
            
    postgres:
        image: postgres:13-alpine
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        networks:
            - sail
        volumes:
            - postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}"]
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    sail:
        driver: bridge

volumes:
    redis-data:
        driver: local
    postgres-data:
        driver: local
